### ISSUE TITLE
Plugin does not work

### ISSUE THREAD

**Issue by freakexeuLow** [Hexer10/HexRedirect#4]
Hey Papero, so i try too running your plugin, but i get this error
https://forums.alliedmods.net/showpost.php?p=2630338&postcount=15

So why i send this again here? I think you will be notified faster here :3

**Comment by Hexer10** [comment]
Actually there should be a PHP error in that tab, but afaik the steam browser default background is black so you can't see the text, if you don't select it, btw I'm gonna style that page to see properly the error hopefully

**Comment by Hexer10** [comment]
https://github.com/Hexer10/HexRedirect/commit/c7a38bc47e18b5a744dbf9363fbb7b31d996d130 
After that commit the steam browser should display a proper error, and try to set `DEV_MODE` to `1`.
To see the changes update your PHP file to this: https://raw.githubusercontent.com/Hexer10/HexRedirect/master/WebServer/redirect.php

**Comment by Hexer10** [comment]
Adding the `openid.php` should fix the issues. if not please do what told in the previous comment.
I apologize for this since also kgns reported this problem in his pr.

**Comment by JamsRepos** [comment]
Still does not work for me, DEV_MODE isn't doing anything either as it's instantly directing and I have no error_log file.

EDIT: In my database, the token and URL is both my IP.

**Comment by freakexeuLow** [comment]
not really Hexer, when users click on the Server Website on the left side, they always show google.com and yes, the user write before !homepage or !forum.^^

**Comment by kgns** [comment]
i think you should focus on https://github.com/Hexer10/HexRedirect/tree/php-db branch, otherwise the plugin does not have a future as people and game hosters will not be able to run this on multiple servers they own/rent

moving every logic to php also prevents timezone usage, date time differences between servers etc

also people having black screen error, check your nginx or apache error logs on the php hosting you use. error messages will be there (all fixed in https://github.com/Hexer10/HexRedirect/tree/php-db branch btw)

**Comment by JamsRepos** [comment]
> i think you should focus on https://github.com/Hexer10/HexRedirect/tree/php-db branch, otherwise the plugin does not have a future as people and game hosters will not be able to run this on multiple servers they own/rent
> 
> moving every logic to php also prevents timezone usage, date time differences between servers etc
> 
> also people having black screen error, check your nginx or apache error logs on the php hosting you use. error messages will be there (all fixed in https://github.com/Hexer10/HexRedirect/tree/php-db branch btw)

Are you talking to us or Hexer? I'm confused on this.

**Comment by kgns** [comment]
if i havent specifically named anyone then im probably talking to anyone who is reading and interested.

on the last statement, its specified that its for "people having black screen error"

**Comment by JamsRepos** [comment]
> if i havent specifically named anyone then im probably talking to anyone who is reading and interested.
> 
> on the last statement, its specified that its for "people having black screen error"

I was getting the black screen error on the version prior to the changes, now all I get is my IP as the target URL.

**Comment by kgns** [comment]
how is that a valid reply to "check your nginx or apache error logs on the php hosting you use. error messages will be there"

**Comment by JamsRepos** [comment]
> how is that a valid reply to "check your nginx or apache error logs on the php hosting you use. error messages will be there"

Seeing as the only reason the IP would be in the database is due to the plugin inserting it, it would have no validity. 

EDIT: I've checked regardless and there's no errors.

**Comment by kgns** [comment]
what i meant is, why are you quoting me when asking for help? im not the repo owner, i just suggested that you check your nginx/apache error logs if you are one of the people who have the problem of getting a black screen.

**Comment by JamsRepos** [comment]
> what i meant is, why are you quoting me when asking for help? im not the repo owner, i just suggested that you check your nginx/apache error logs if you are one of the people who have the problem of getting a black screen.

I wasn't asking for help from you, was just wondering who your message was aimed at. Sorry for the confusion and I'm only quoting you in response to your previous message.

**Comment by kgns** [comment]
jesus christ, and thats why i asked what i asked. you quoted a message of mine and said something irrelevant (which you call a response to it)

anyway, anyone who is interested in this plugin (including the repo owner) should focus on php-db branch

**Comment by Hexer10** [comment]
I've done progresses on that in #5
By tomorrow I should be able to merge the pr, it just needs some more tests.

**Comment by Hexer10** [comment]
#5 Just merged!
